name: crypto

dependencies:
  - base
  - text
  - vector
  # - criterion

library:
  source-dirs: src


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - crypto


executables:
 cripto-exe:
   main: Main.hs
   source-dirs: app
   dependencies:
     - crypto
