name: crypto

dependencies:
  - base
  - text
  - vector
  # - criterion

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - crypto

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - crypto
