name: crypto

dependencies:
  - base
  - text
  - vector
  # - criterion
  - QuickCheck 
  - JuicyPixels
  - either
  - bytestring

library:
  source-dirs: src


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - crypto


executables:
 crypto-exe:
   main: Main.hs
   source-dirs: app
   dependencies:
     - crypto
